### ISSUE TITLE
这个录像播放器怎么使用的

### ISSUE THREAD

**Issue by xiaohuazi123** [jumpserver/VideoPlayer#1]
请问这个录像播放器怎么使用的
是纯前端项目？
如果是纯前端项目怎么播放录像文件？

**Comment by orangemio** [comment]
这是配合JumpServer 新版本提供的录像下载功能进行播放的。

下载录像后使用录像播放器播放录像。

**Comment by xiaohuazi123** [comment]
请问有教程或截图吗？
